//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelchairBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Responses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Responses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WheelchairBot.Responses", typeof(Responses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured: Joe was previously disconnected and now cannot leave and rejoin..
        /// </summary>
        internal static string join_DisconnectReconnectTimeout {
            get {
                return ResourceManager.GetString("join_DisconnectReconnectTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oh my god {0} I LITERALLY CANT BE IN 2 PLACES AT ONCE. I am already in {1}.
        /// </summary>
        internal static string join_JoeInDifferentChannel {
            get {
                return ResourceManager.GetString("join_JoeInDifferentChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get some glasses, I am already in {0}.
        /// </summary>
        internal static string join_JoeInSameChannel {
            get {
                return ResourceManager.GetString("join_JoeInSameChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hello vro 🤑🤑🤑 I connected to {0}.
        /// </summary>
        internal static string join_JoinSuccess {
            get {
                return ResourceManager.GetString("join_JoinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join voice channel thread has timed out, start panicking.
        /// </summary>
        internal static string join_Timeout {
            get {
                return ResourceManager.GetString("join_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hey peter, get a load of this dumbass tryna get me to join a channel without being in one lmao.
        /// </summary>
        internal static string join_UserNotInChannel {
            get {
                return ResourceManager.GetString("join_UserNotInChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guys, I think {0} is schizophrenic, im not in any voice channels.
        /// </summary>
        internal static string leave_JoeNotInChannel {
            get {
                return ResourceManager.GetString("leave_JoeNotInChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later losers.
        /// </summary>
        internal static string leave_Left {
            get {
                return ResourceManager.GetString("leave_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tenor.com/view/joeswanson-stand-walk-family-guy-gif-17739079.
        /// </summary>
        internal static string leave_LeftGif {
            get {
                return ResourceManager.GetString("leave_LeftGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave voice channel thread has timed out, start panicking.
        /// </summary>
        internal static string leave_Timeout {
            get {
                return ResourceManager.GetString("leave_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop being a party pooper, you arent even listening to my music.
        /// </summary>
        internal static string leave_UserNotInChannel {
            get {
                return ResourceManager.GetString("leave_UserNotInChannel", resourceCulture);
            }
        }
    }
}
